### ISSUE TITLE
Gaps in line charts

### ISSUE THREAD

**Issue by MaximMoinat** [EHDEN/NetworkDashboards#10]
If some series have no y-value for a given x-value, then gaps in the line appear (nulls). We should have the option to draw the lines between the points even if there are null values in between.

In the example below, the purple line has all x-values, but the other lines do not. 
![image](https://user-images.githubusercontent.com/17825660/69983323-53649100-152e-11ea-8dea-9e78f4e362f0.png)

**Comment by aspedrosa** [comment]
This might be possible to correct with the **resample** feature under Advanced Analytics -> Python Functions -> pandas.resample
