### ISSUE TITLE
Explain how network dashboards work

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/NetworkDashboards#133]
Can you explain how it works that you only show the data for that database?

I added Data Density Plot in Data Domains, Number of Observation periods in Observation Period, Visit Age Distribution in Visit, Updated Concept Browser they all need to change to only show that database, e.g. IPCI

**Comment by joaorafaelalmeida** [comment]
I think it is better to discuss this tomorrow in a TC.
