### ISSUE TITLE
Maximize the window

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/NetworkDashboards#134]
![image](https://user-images.githubusercontent.com/7252105/102273565-cd419f80-3f22-11eb-968c-6ec5520dab7f.png)

Can we maximize the place holder for the database level plots so it does not cut-off the information

**Comment by PRijnbeek** [comment]
Is there a css to remove the database-level Dashboard and Published Title?

**Comment by joaorafaelalmeida** [comment]
Yes, we usually apply this CSS code to remove the header which includes the title, edition button and the star.
```
.button-container { /* edit button */
    display: none !important;
}
.favstar {
    display: none !important;
}
.dashboard > div:not(.dashboard-content) { /* dashboard header */
    display: none;
}
```

**Comment by joaorafaelalmeida** [comment]
I already applied it in this dashboard.

**Comment by PRijnbeek** [comment]
The window is still not maximised

**Comment by PRijnbeek** [comment]
![image](https://user-images.githubusercontent.com/7252105/103034764-ecb17b80-4565-11eb-9c72-91dd5242b1d1.png)

See it is still not maximized in the container of the page

**Comment by joaorafaelalmeida** [comment]
@PRijnbeek Can you please check if this is already ok in your screen?
