### ISSUE TITLE
New Vizplugin for pie charts

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/NetworkDashboards#141]
See this https://superset-demo.dev.apps.nielsen.com/superset/dashboard/viz_plugins/

see also this post: https://apache-superset.slack.com/archives/CK1P3L23E/p1608670857146100

**Comment by PRijnbeek** [comment]
I also noticed the one in master does work in safari and they also improved the filter functionality

![image](https://user-images.githubusercontent.com/7252105/103033887-e02c2380-4563-11eb-8606-67c472717e7e.png)

**Comment by aspedrosa** [comment]
I found out what was wrong with pie charts. There was missing a permission on the public role and I already added.
Check if it renders on your side.
