### ISSUE TITLE
Remove the submenu in the portal

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/NetworkDashboards#144]
![image](https://user-images.githubusercontent.com/7252105/103034353-f8507280-4564-11eb-9367-a99867dadbc3.png)

Make the main "Dashboards" go directly to the dashboard (there is only one now)

**Comment by PRijnbeek** [comment]
i am showing the portal to people and more people are getting access. can we prioritise this? is this something i could fix in the backend maybe? thanks

**Comment by joaorafaelalmeida** [comment]
Done
