### ISSUE TITLE
Change order RC, DRC in network coverage table

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/NetworkDashboards#149]
![image](https://user-images.githubusercontent.com/7252105/103778204-386a2780-5032-11eb-980d-5be2e2b6dfa0.png)

reverse this order to be consistent with the one above. I am not allowed to update it myself.

**Comment by aspedrosa** [comment]
Tried to fix and you can only order by one column/metric. I order it by **rc**.

Note: You can add yourself to the owners list of the chart to edit it.
