### ISSUE TITLE
Customise message when there are no results

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/NetworkDashboards#151]
![image](https://user-images.githubusercontent.com/7252105/103805210-95c2a080-5053-11eb-9ca8-c472ec75e610.png)

Is there a way to change this message?

**Comment by aspedrosa** [comment]
This currently is hardcoded :/
https://github.com/apache-superset/superset-ui/blob/master/packages/superset-ui-core/src/chart/components/NoResultsComponent.tsx

**Comment by PRijnbeek** [comment]
added a feature request:

https://github.com/apache-superset/superset-ui/issues/893

**Comment by joaorafaelalmeida** [comment]
I assigned this to myself because I want to try something to see if it solves this problem.
