### ISSUE TITLE
Space of table

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/NetworkDashboards#165]
<img width="1573" alt="image" src="https://user-images.githubusercontent.com/7252105/106198141-f1e09680-61b3-11eb-9311-8c68cfc24dbc.png">

Needs more space so it can show at least 5 databases with the scrollbar, I cannot edit it so can you change this?

**Comment by PRijnbeek** [comment]
Same for this one: 

<img width="1573" alt="image" src="https://user-images.githubusercontent.com/7252105/106198480-5e5b9580-61b4-11eb-8997-976c5f94e69b.png">

**Comment by joaorafaelalmeida** [comment]
I resized both, but you should be able to do it.
