### ISSUE TITLE
Filter outliers before visualising data

### ISSUE THREAD

**Issue by MaximMoinat** [EHDEN/NetworkDashboards#237]
We are seeing some outliers in the DatabaseCatalogue due to data quality issues. For example, a negative Cumulative Observation Time (Observation Period). Or default start dates set on 1900-01-01. This makes the data visualisations harder to interpret. 

We should hide these outliers such that the visualisations are more focused on the real data. This filtering can be implemented upon processing of the uploaded file (e.g. remove any negative values) or when visualising the data. The former has my preference, as this would also allow giving direct feedback to the uploader on what data is 'rejected'. See also issue #236.

**Comment by aspedrosa** [comment]
See [this](https://github.com/EHDEN/NetworkDashboards/issues/232#issuecomment-1109970969) comment. This way the outlier data is still accessible to the user.

**Comment by MaximMoinat** [comment]
Thanks, that would be a nice solution indeed to implement for all time ranges.
