### ISSUE TITLE
New type concepts missing in provenance dashboard

### ISSUE THREAD

**Issue by MaximMoinat** [EHDEN/NetworkDashboards#247]
## Expected Behaviour
In the provenance tab, we expect all the occurring type concepts to be shown.

## Current Behaviour
Only a subset of type concepts are shown. It seems that only the old (now non-standard) type concepts and none of the new concepts. For instance, we expect the generic ['EHR' type concept](https://athena.ohdsi.org/search-terms/terms/32817) to show as well.
![image](https://user-images.githubusercontent.com/17825660/173361607-5f763213-3617-4c92-864a-6809ba68b716.png)

## Possible Solution
I suspect that an old version of the OMOP vocabulary (pre August 2020) is used.  Due to the inner join made on the concept table, we loose the newly added type concepts.

## Possible Implementation
The implementation can be two-fold:
 - Update the OMOP vocabulary (and keep this updated for all major releases)
 - Change the `inner join` in the query below, by a `left join`. If concept does not exist, use the type_concept_id instead of the concept_name such that the count will show in the dashboard.
https://github.com/EHDEN/NetworkDashboards/blob/a745c69649372bffdd5a3790ae8dda4810d22216/docs/src/09-provenance.Rmd#L73-L76

**Comment by aspedrosa** [comment]
I updated the OMOP vocabulary and more entries are showing now.

**Comment by MaximMoinat** [comment]
Thanks, looks like this issue is solved. Thanks.
