### ISSUE TITLE
Change the left-menu style-sheet

### ISSUE THREAD

**Issue by joaorafaelalmeida** [EHDEN/NetworkDashboards#28]
Adopt the style-sheet used on the left-menu of the EHDEN Portal (Figure below)

![newSubMenu](https://user-images.githubusercontent.com/17878072/81428675-7e45b780-9154-11ea-9931-2662f75dbeae.png)

**Comment by aspedrosa** [comment]
The app that styles this is no longer in use. Closed by #148
