### ISSUE TITLE
Updating Achilles results is not working

### ISSUE THREAD

**Issue by joaorafaelalmeida** [EHDEN/NetworkDashboards#34]
When I tried to update the Achilles results from an existent database, the system removed the data from the dashboards but didn't update with the new information.

**Comment by aspedrosa** [comment]
This happens because I'm inserting the new records into the achilles_results table and then moving all records, associated with the datasource, to the archive table.

This is already fixed on #26, [here](https://github.com/EHDEN/cdm-bi/pull/26/files#diff-201ced2e0df1d9a4e07c898545e9306a)

**Comment by aspedrosa** [comment]
Fixed with #26
