### ISSUE TITLE
Custom tick marks

### ISSUE THREAD

**Issue by MaximMoinat** [EHDEN/NetworkDashboards#8]
Option to create custom tick marks (e.g. 1900, 1925, 1950, 1975, 2000)

**Comment by aspedrosa** [comment]
I didn't find any issues or pull request regarding this on the superset repository.
I found some solutions that make use of some sql logic
- https://dba.stackexchange.com/questions/195353/grouping-data-into-5-minute-intervals-within-a-time-range
- https://dba.stackexchange.com/a/232672
