### ISSUE TITLE
Create line chart without datetime axis

### ISSUE THREAD

**Issue by MaximMoinat** [EHDEN/NetworkDashboards#9]
No option to plot two continuous variables as line graph. Only possible if one variable is a date.

E.g. to plot percentage of people vs number of days.

**Comment by aspedrosa** [comment]
Currently this is not possible. There are already several issues requesting this feature on seperset's repository ([\#6568](https://github.com/apache/incubator-superset/issues/6568), [\#3184](https://github.com/apache/incubator-superset/issues/3184)) and a pull request was created but it wasn't merged ([\#4185](https://github.com/apache/incubator-superset/pull/4185)).
On superset-ui-plugins repository they said that is on their roadmap for this year, [here](https://github.com/apache-superset/superset-ui-plugins/issues/51#issuecomment-609369688).
