### ISSUE TITLE
Concepts Browser magnitudes - more easy to interprete numbers

### ISSUE THREAD

**Issue by MaximMoinat** [EHDEN/NetworkDashboards#98]
##  Expected Behavior

When [browsing the concepts](https://portal.ehden.eu/c/EHDEN/apps/cp/dashboard/General%20Concepts), I would like to quickly see whether a concept occurs a lot or not.

## Current Behavior

There are a lot of numbers to indicate a certain magnitude, making it hard to interpret quickly. e.g. the difference between `10^2-10^3` and `10^5-10^6` is 2 characters out of 10. Almost indistinguishable at a first look.
![image](https://user-images.githubusercontent.com/17825660/94440996-83a6ab80-01a2-11eb-99b4-481f4dfd1d21.png)

## Possible Solution

Adding a colour gradient (similar to an heat map) as the fill of the cell.

**Comment by MaximMoinat** [comment]
Also, I would remove the magnitude_counts. Maybe replace with a column 'occurrences per person'. (as also done with the original Data Sources treemap)

**Comment by PRijnbeek** [comment]
We are changing this now to round up to the nearest multiple of 100 which much better. We added the per_person. Will close when finalized

**Comment by PRijnbeek** [comment]
Fix my multiples of 100
