### ISSUE TITLE
Data Domains: Records per person

### ISSUE THREAD

**Issue by MaximMoinat** [EHDEN/NetworkDashboards#99]
The [Data Domains](https://portal.ehden.eu/c/EHDEN/apps/cp/dashboard/Data%20Domains) page shows an average number of records per patient for the number of unique persons in that domain. This might be confusing, e.g. see the screenshot below showing 1.7 device records per person. That is a bit much over the whole population.
![image](https://user-images.githubusercontent.com/17825660/94454177-d340a380-01b1-11eb-8b98-1742b9d9dd1d.png)

So I would suggest to take the whole population as the denominator.

**Comment by PRijnbeek** [comment]
Yes agree will require some SQL magic but will look into it
